export const Products = [
    {
      id: 1,
      brand_name : "SHAZNAVI RUGS",
      stock : 20,
      title: "Shaznavi Modern Shag Rugs Luxurious Soft Handmade Shaggy Carpets ( Micro Silk, Multi )",
      price: 5199,
      description: "This traditional style premium collection area shaggy rugs super soft handwoven shag for home living room bedroom rugs is made of with natural micro silk wool and fine colours which give super soft shaggy handmade carpets for living room bedroom home gallery banquet hall and anywhere in your house. Dear Buyer we take more days for longer size.",
      category: "carpets and rugs",
      model : "geometric",
      pile : "High Pile",
      color : "Red",
      image:  [
        "https://www.obeetee.in/cdn/shop/products/2004710001_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2004710001-top_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2_8eb80646-4de9-4664-b060-2ab78ac0edda_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/44_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/4_8_900x.jpg?v=1674140035",
      ],
      rating: {
        rate: 4.9,
        count: 120,
      },
    },
    {
      id: 2,
      brand_name : "SHAZNAVI RUGS",
      stock : 20,
      title: "Shaznavi Modern Shag Rugs Luxurious Soft Handmade Shaggy Carpets ( Micro Silk, Multi )",
      price: 5199,
      description: "This traditional style premium collection area shaggy rugs super soft handwoven shag for home living room bedroom rugs is made of with natural micro silk wool and fine colours which give super soft shaggy handmade carpets for living room bedroom home gallery banquet hall and anywhere in your house. Dear Buyer we take more days for longer size.",
      category: "carpets and rugs",
      model : "geometric",
      pile : "High Pile",
      color : "Red",
      image:  [
        "https://www.obeetee.in/cdn/shop/products/2004710001_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2004710001-top_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2_8eb80646-4de9-4664-b060-2ab78ac0edda_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/44_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/4_8_900x.jpg?v=1674140035",
      ],
      rating: {
        rate: 4.9,
        count: 120,
      },
    },
    {
      id: 3,
      brand_name : "SHAZNAVI RUGS",
      stock : 20,
      title: "Shaznavi Modern Shag Rugs Luxurious Soft Handmade Shaggy Carpets ( Micro Silk, Multi )",
      price: 5199,
      description: "This traditional style premium collection area shaggy rugs super soft handwoven shag for home living room bedroom rugs is made of with natural micro silk wool and fine colours which give super soft shaggy handmade carpets for living room bedroom home gallery banquet hall and anywhere in your house. Dear Buyer we take more days for longer size.",
      category: "carpets and rugs",
      model : "geometric",
      pile : "High Pile",
      color : "Red",
      image:  [
        "https://www.obeetee.in/cdn/shop/products/2004710001_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2004710001-top_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2_8eb80646-4de9-4664-b060-2ab78ac0edda_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/44_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/4_8_900x.jpg?v=1674140035",
      ],
      rating: {
        rate: 4.9,
        count: 120,
      },
    },
    {
      id: 4,
      brand_name : "SHAZNAVI RUGS",
      stock : 20,
      title: "Shaznavi Modern Shag Rugs Luxurious Soft Handmade Shaggy Carpets ( Micro Silk, Multi )",
      price: 5199,
      description: "This traditional style premium collection area shaggy rugs super soft handwoven shag for home living room bedroom rugs is made of with natural micro silk wool and fine colours which give super soft shaggy handmade carpets for living room bedroom home gallery banquet hall and anywhere in your house. Dear Buyer we take more days for longer size.",
      category: "carpets and rugs",
      model : "geometric",
      pile : "High Pile",
      color : "Red",
      image:  [
        "https://www.obeetee.in/cdn/shop/products/2004710001_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2004710001-top_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/2_8eb80646-4de9-4664-b060-2ab78ac0edda_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/44_900x.jpg?v=1674140035",
        "https://www.obeetee.in/cdn/shop/products/4_8_900x.jpg?v=1674140035",
      ],
      rating: {
        rate: 4.9,
        count: 120,
      },
    },
]
   